services:
  sftp-checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sftp-checker
    env_file:
      - .env
    volumes:
      - ./logs:/logs
      - ./alerted-files:/alerted-files
    restart: unless-stopped
